[template]
exclude = [".venv", "target", ".github/workflows/build-release.yaml"]

[template.variables]
project_name = { type = "string", prompt = "Project name (e.g., my_rust_python)"}
project_description = { type = "string", prompt = "Project description", default = "A Python extension module written in Rust using PyO3" }
author_name = { type = "string", prompt = "Author name", default = "Your Name" }
author_email = { type = "string", prompt = "Author email", default = "your.email@example.com" }
python_min_version = { type = "string", prompt = "Minimum Python version (e.g., 3.9)", default = "3.9"}
license = { type = "string", prompt = "License (MIT/Apache-2.0/BSD-3-Clause)", default = "Apache-2.0"}
